routes/web.php
<?php

use App\Http\Controllers\MainController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', [MainController::class, 'index']);

Route::group(['prefix' => 'cms'], function () {
    Auth::routes([
        'register' => false, // Registration Routes...
        'reset' => false, // Password Reset Routes...
        'verify' => false, // Email Verification Routes...
    ]);
});

Route::group(['middleware' => ['auth']], function(){
    Route::post('post/upload', [PostController::class, 'upload'])->name('post.upload');
    Route::resource('posts', PostController::class);

    Route::patch('users/update-profile', [UserController::class, 'update_profile'])->name('users.update-profile');
    Route::get('users/edit-profile', [UserController::class, 'edit_profile'])->name('users.edit-profile');
    Route::resource('users', UserController::class);
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('articles', [PostController::class, 'list'])->name('articles.list');
Route::get('articles/{slug}', [PostController::class, 'detail'])->name('articles.detail');

app/Models/Post.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getDate()
    {
        return Carbon::parse($this->created_at)->translatedFormat('l, d F Y');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class PostController extends Controller
{
    public function index()
    {
        // If not use Gate
        // $posts = Post::where('user_id', Auth::user()->id)
        //             ->orderBy('created_at', 'desc')
        //             ->get();

        $posts = Post::all();
        return view('backend.posts.index', ['posts' => $posts]); 
    }

    public function create()
    {
        return view('backend.posts.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'status' => 'required'
        ]);

        Post::create([
            'title' => $request->title,
            'description' => $request->description,
            'status' => $request->status,
            'slug' => Str::slug($request->title, '-'),
            'user_id' => $request->user()->id
        ]);

        return redirect()->route('posts.index')->with('success', 'Post has been created!');
    }

    public function edit($id)
    {
        $post = Post::find($id);
        $this->authorize('update-post', $post);
        return view('backend.posts.edit', ['post' => $post]);
    }

    public function update(Request $request, $id)
    {
        $post = Post::find($id);
        $this->authorize('update-post', $post);
        $post->update([
            'title' => $request->title,
            'description' => $request->description,
            'status' => $request->status,
            'slug' => Str::slug($request->title, '-')
        ]);

        return redirect()->route('posts.index')->with('success', 'Post has been updated!');
    }

    public function destroy($id)
    {
        $post = Post::find($id);
        $this->authorize('delete-post', $post);
        $post->delete();

        return redirect()->route('posts.index')->with('success', 'Post has been deleted!');
    }

    public function upload(Request $request)
    {
        if ($request->hasFile('upload')) {
            $originName = $request->file('upload')->getClientOriginalName();
            $fileName = pathinfo($originName, PATHINFO_FILENAME);
            $extension = $request->file('upload')->getClientOriginalExtension();
            $fileName = $fileName . '_' . time() . '.' . $extension;

            $request->file('upload')->move(public_path('images'), $fileName);

            $CKEditorFuncNum = $request->input('CKEditorFuncNum');
            $url = asset('images/' . $fileName);
            $msg = 'Image uploaded successfully';
            $response = "<script>window.parent.CKEDITOR.tools.callFunction($CKEditorFuncNum, '$url', '$msg')</script>";

            @header('Content-type: text/html; chartset=utf-8');
            echo $response;
        }
    }

    public function list()
    {
        $posts = Post::simplePaginate(6);
        return view('frontend.posts.index', ['posts' => $posts]);
    }

    public function detail($slug)
    {
        $post = Post::where('slug', $slug)->first();
        return view('frontend.posts.detail', ['post' => $post]);
    }
}

resources/views/backend/posts/create.blade.php
@extends('layouts.backend.dashboard.master')

@section('title', 'Post Create')

@section('content')
<div class="container">
    <div class="card shadow">
        <div class="card-header">Create Post</div>
        <div class="card-body">
            <form action="{{ route('posts.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="title">Title</label>
                    <input id="title" class="form-control @error('title') is-invalid @enderror" type="text" name="title"
                        value="{{ old('title') }}">

                    @error('title')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea id="description" class="form-control @error('description') is-invalid @enderror"
                        name="description" rows="3">{{ old('description') }}</textarea>

                    @error('description')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="status">Status</label>
                    <select id="status" class="form-control @error('status') is-invalid @enderror" name="status">
                        <option value="">-- Select Status --</option>
                        <option value="active" {{ old('status') == 'active' ? 'selected' : '' }}>Active</option>
                        <option value="inactive" {{ old('status') == 'inactive' ? 'selected' : '' }}>Inactive</option>
                    </select>

                    @error('status')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{ route('posts.index') }}" class="btn btn-success">Back</a>
            </form>
        </div>
    </div>
</div>
@endsection

@push('script')
    <script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>
    <script>
        // CKEDITOR.replace('description');
        CKEDITOR.replace('description', {
            filebrowserUploadUrl: "{{ route('post.upload', ['_token' => csrf_token() ]) }}",
            filebrowserUploadMethod: 'form',
            disallowedContent: 'img{width,height};'
        });
    </script>
@endpush

resources/views/backend/posts/edit.blade.php
@extends('layouts.backend.dashboard.master')

@section('title', 'Post Edit')

@section('content')
<div class="container">
    <div class="card shadow">
        <div class="card-header">Edit Post</div>
        <div class="card-body">
            <form action="{{ route('posts.update', $post->id) }}" method="POST">
                @csrf
                @method('PATCH')

                <div class="form-group">
                    <label for="title">Title</label>
                    <input id="title" class="form-control @error('title') is-invalid @enderror" type="text" name="title"
                        value="{{ old('title', $post->title) }}">

                    @error('title')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea id="description" class="form-control @error('description') is-invalid @enderror"
                        name="description" rows="3">{{ old('description', $post->description) }}</textarea>

                    @error('description')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="status">Status</label>
                    <select id="status" class="form-control @error('status') is-invalid @enderror" name="status">
                        <option value="">-- Select Status --</option>
                        <option value="active" 
                            {{ old('status') == 'active' ? 'selected' : '' }}
                            {{ $post->status == 'active' ? 'selected' : '' }}>
                            Active
                        </option>
                        <option value="inactive" 
                            {{ old('status') == 'inactive' ? 'selected' : '' }}
                            {{ $post->status == 'inactive' ? 'selected' : '' }}>
                            Inactive
                        </option>
                    </select>

                    @error('status')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{ route('posts.index') }}" class="btn btn-success">Back</a>
            </form>
        </div>
    </div>
</div>
@endsection

@push('script')
    <script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>
    <script>
        // CKEDITOR.replace('description');
        CKEDITOR.replace('description', {
            filebrowserUploadUrl: "{{ route('post.upload', ['_token' => csrf_token() ]) }}",
            filebrowserUploadMethod: 'form',
            disallowedContent: 'img{width,height};'
        });
    </script>
@endpush

resources/views/backend/posts/index.blade.php
@extends('layouts.backend.dashboard.master')

@section('title', 'List Posts')

@section('content')
<div class="container">
    @include('layouts.backend.dashboard.include.message')
    <div class="row">
        <div class="col-md-10"></div>
        <div class="col-md-2">
            <a href="{{ route('posts.create') }}" class="btn btn-success mb-4">Create</a>
        </div>
    </div>
    <div class="row">
        @forelse ($posts as $post)    
            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-9">
                                <h5 class="card-title">{{ $post->title }}</h5>
                            </div>
                            <div class="col-md-3">
                                <span class="badge badge-{{ $post->status == 'inactive' ? 'danger' : 'success' }}">
                                    {{ $post->status == 'inactive' ? 'Inactive' : 'Active' }}
                                </span>
                            </div>
                        </div>
                        <p class="card-text">{!! substr($post->description,0,100) !!}...</p>
                        
                        @can('update-post', $post)
                            <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-primary">Edit</a>
                        @endcan

                        @can('delete-post', $post)    
                            <button id="delete" data-title="{{ $post->title }}"
                                href="{{ route('posts.destroy', $post->id) }}" class="btn btn-danger btn-sm d-inline">
                                <i class="zmdi zmdi-delete zmdi-hc-fw" style="color: #fff; font-size: 1.5em;"></i>
                                Delete
                            </button>
                        @endcan

                        <form method="post" id="deleteForm">
                            @csrf
                            @method("DELETE")
                            <input type="submit" value="" style="display:none;">
                        </form>
                    </div>
                </div>
            </div>
        @empty
            <h4 class="text-center">No Posts</h4>
        @endforelse
    </div>
</div>
@endsection

@push('script')
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        $('button#delete').on('click', function(){
            var href = $(this).attr('href');
            var title = $(this).data('title');

            swal({
                title: "Apakah Anda yakin ingin menghapus "+ title,
                text: "",
                icon: "warning",
                buttons: true,
                dangerMode: true,
                })
                .then((willDelete) => {
                if (willDelete) {
                    document.getElementById('deleteForm').action = href;
                    document.getElementById('deleteForm').submit();
                    swal("Video berhasil dihapus!", {
                        icon: "success",
                    });
                }
            });
        });
    </script>
@endpush